FROM ishotihadus/ruby:latest

ARG MAKE_OPTIONS

RUN set -eux && \
  \
  apt-get -y update && \
  apt-get -y upgrade && \
  apt-get -y install --no-install-recommends \
  curl \
  libfontconfig-dev \
  libfreetype-dev \
  libjpeg-dev \
  libltdl-dev \
  libomp-dev \
  libpng-dev \
  && \
  \
  apt-get -y clean && \
  rm -rf /var/lib/apt/lists/* && \
  \
  cd /tmp && \
  curl -L https://imagemagick.org/download/ImageMagick-7.1.0-55.tar.gz | tar xzf - && \
  cd /tmp/ImageMagick-7.1.0-55 && \
  ./configure --enable-shared --with-modules --with-jemalloc --disable-docs && \
  make install $MAKE_OPTIONS && \
  cd / && rm -rf /tmp/ImageMagick-7.1.0-55 && \
  ldconfig -v && \
  \
  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false curl && \
  apt-get clean -y && rm -rf /var/lib/apt/lists/*
