FROM ishotihadus/ruby-rmagick:latest

RUN set -eux && \
  \
  apt-get -y update && \
  apt-get -y upgrade && \
  apt-get -y install --no-install-recommends \
  curl \
  libcairo2-dev \
  libcerf-dev \
  libgd-dev \
  libpango1.0-dev \
  locales \
  && \
  \
  apt-get -y clean && \
  rm -rf /var/lib/apt/lists/* && \
  \
  sed -i -E 's/^# en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen && \
  locale-gen en_US.UTF-8 && \
  \
  cd /tmp && \
  curl -L https://sourceforge.net/projects/gnuplot/files/gnuplot/5.4.5/gnuplot-5.4.5.tar.gz | tar xzf - && \
  cd /tmp/gnuplot-5.4.5 && \
  ./configure && \
  make install && \
  cd / && rm -rf /tmp/gnuplot-5.4.5 && \
  \
  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false curl && \
  apt-get clean -y && rm -rf /var/lib/apt/lists/*
